{
 "title": "Restauranty",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total request rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(http_requests_total{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 400er error rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(http_requests_total{namespace=\"restauranty-lily\", statusCode=~\"4..\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 500er error rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(http_requests_total{namespace=\"restauranty-lily\", statusCode=~\"5..\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500er error by service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (container) (\n  rate(http_requests_total{namespace=\"restauranty-lily\", statusCode=~\"5..\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request volume by service",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (\n  rate(http_requests_total{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by status Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (statusCode) (\n  rate(http_requests_total{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by route",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (container, route) (\n  rate(http_requests_total{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per second by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (container) (\n  rate(http_requests_total{namespace=\"restauranty-lily\", route!=\"/metrics\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (container) (\n  rate(http_request_duration_seconds_sum{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n)\n/\nsum by (container) (\n  rate(http_request_duration_seconds_count{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, container) (\n    rate(http_request_duration_seconds_bucket{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, container) (\n    rate(http_request_duration_seconds_bucket{namespace=\"restauranty-lily\", route!=\"/metrics\"}[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}