apiVersion: v1
kind: Secret
metadata:
  name: restauranty-secrets
  namespace: restauranty-lily
type: Opaque
stringData:
  SECRET: "Lily'sSecret"
  MONGODB_URI: "mongodb://mongo:27017/restauranty"
  CLOUD_API_KEY: "638252417449569"
  CLOUD_API_SECRET: "Dkjp5CympkEYNsH9-qi-hfZM9-k"
  CLOUD_NAME: "dgmgwjok1"