name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push images
        run: docker buildx bake --push --set auth.tags=lilywalch/restauranty-auth-service:${IMAGE_TAG} --set discounts.tags=lilywalch/restauranty-discounts-service:${IMAGE_TAG} --set items.tags=lilywalch/restauranty-items-service:${IMAGE_TAG} --set client.tags=lilywalch/restauranty-client-service:${IMAGE_TAG}

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify cluster connection
        run: kubectl get nodes

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Deploy tagged images
        run: |
          kubectl set image deployment/auth-deployment auth=lilywalch/restauranty-auth-service:${IMAGE_TAG} -n restauranty-lily
          kubectl set image deployment/discounts-deployment discounts=lilywalch/restauranty-discounts-service:${IMAGE_TAG} -n restauranty-lily
          kubectl set image deployment/items-deployment items=lilywalch/restauranty-items-service:${IMAGE_TAG} -n restauranty-lily
          kubectl set image deployment/client-deployment client=lilywalch/restauranty-client-service:${IMAGE_TAG} -n restauranty-lily

      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/auth-deployment -n restauranty-lily
          kubectl rollout status deployment/items-deployment -n restauranty-lily
          kubectl rollout status deployment/discounts-deployment -n restauranty-lily
          kubectl rollout status deployment/client-deployment -n restauranty-lily